int max_quantity(struct bot *b, struct location *l);
int cargo_rvolume(struct bot *b);
int cargo_rweight(struct bot *b);
int shortest_distance(struct location *s, struct location *b);
int max_availible_quantity(struct bot *bt, struct location *s, struct location *b);
double average_fuel_cost(struct bot *bt);
int can_reach_fuelstation(struct bot *bt, struct location *l, int size, int negfuel);
int max_availible_profit_real(struct bot *bt, struct location *s, struct location *b);
int get_map_size(struct bot *bt);
int selling_profit(struct bot *bt, struct location *b);
int buyer_score(struct bot *bt, struct location *b);
int seller_score(struct bot *bt, struct location *s);
double average_fuel_cost(struct bot *bt);
int start_other_score(struct bot *bt, struct location *l);
int fuel_station_score(struct bot *bt, struct location *f);
int dump_score(struct bot *bt, struct location *l);
int shortest_distance_index(int index, int size);
int available_move(struct bot* bt, int distance);
int max_fuel_quantity(struct bot *bt, struct location *f);
int remaining_fuel_quantity(struct bot *bt);
int cannot_reach_fuel_station(struct bot *bt);
struct location *most_profit_buyer(struct bot *bt, struct location *s);
int turns_required(struct bot *bt, int moves);
int reachable_fuel_station_quantity(struct bot *bt);
int product_quantity(struct bot *bt, struct location *l);
int need_dump(struct bot *bt);
int total_buyer_quantity(struct location *l);
int all_bots_quantity(struct location *l);
int buyer_location_bots_num(struct location *l);
int buyer_location_bots_quantity(struct location *l);
int fuel_station_num(struct bot *bt);
